config/routes.rb
Rails.application.routes.draw do
  resources :hobbies
  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_scope :user do
    get 'users/find_hobby_partners', to: 'users/registrations#find_hobby_partners', as: 'find_hobby_partners'
    get 'users/profile_export', to: 'users/registrations#profile_export', as: 'profile_export'
  end
  root to: 'pages#home'
  get 'pages/home'
  get 'pages/dashboard'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/hobby.rb
# == Schema Information
#
# Table name: hobbies
#
#  id          :integer          not null, primary key
#  description :text
#  name        :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Hobby < ApplicationRecord
  has_and_belongs_to_many :users, inverse_of: :hobbies
  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  city                   :string           not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  first_name             :string
#  last_name              :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_person_name
  has_and_belongs_to_many :hobbies, inverse_of: :user
  validates :city, presence: true

  # Fetches users who share at least one hobby with the current user.
  #
  # @return [ActiveRecord::Relation] A distinct collection of users with shared hobbies.
  def users_with_shared_hobbies
    User.joins(:hobbies)
        .where(hobbies: { id: hobby_ids })
        .where.not(id:)
        .distinct
  end

  # Fetches users from the same city as the current user.
  #
  # @return [ActiveRecord::Relation] A collection of users from the same city.
  def users_from_same_city
    User.where(city:)
        .where.not(id:)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(
        :first_name,
        :last_name,
        :name,
        :email,
        :city,
        :password,
        :password_confirmation,
        hobby_ids: []
      )
    end

    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(
        :first_name,
        :last_name,
        :name,
        :email,
        :city,
        :password,
        :password_confirmation,
        :current_password,
        hobby_ids: []
      )
    end
  end
end

app/controllers/hobbies_controller.rb
class HobbiesController < ApplicationController
  before_action :set_hobby, only: [:show, :edit, :update, :destroy]

  # GET /hobbies
  def index
    @hobbies = Hobby.all
  end

  # GET /hobbies/1 or /hobbies/1.json
  def show; end

  # GET /hobbies/new
  def new
    @hobby = Hobby.new
  end

  # GET /hobbies/1/edit
  def edit; end

  # POST /hobbies or /hobbies.json
  def create
    @hobby = Hobby.new(hobby_params)

    respond_to do |format|
      if @hobby.save
        format.html { redirect_to @hobby, notice: "Hobby was successfully created." }
        format.json { render :show, status: :created, location: @hobby }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hobby.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hobbies/1 or /hobbies/1.json
  def update
    respond_to do |format|
      if @hobby.update(hobby_params)
        format.html { redirect_to @hobby, notice: "Hobby was successfully updated." }
        format.json { render :show, status: :ok, location: @hobby }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hobby.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hobbies/1 or /hobbies/1.json
  def destroy
    @hobby.destroy!
    respond_to do |format|
      format.html { redirect_to hobbies_url, notice: "Hobby was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_hobby
    @hobby = Hobby.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to hobbies_path
  end

  # Only allow a list of trusted parameters through.
  def hobby_params
    params.require(:hobby).permit(:name, :description)

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to pages_dashboard_path if user_signed_in?
  end

  def dashboard
    redirect_to root_path unless user_signed_in?
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # Get an example user with a matching hobby. Preferably from the same city.
  def find_hobby_partners
    matched_user = MatchMaker::HobbyMatch.call(current_user)

    respond_to do |format|
      format.json { render json: matched_user }
    end
  end

  # Export profile of current_user as CSV
  def profile_export
    ProfileExportJob.perform_inline(current_user.id)
    flash[:notice] = 'Export job has been enqueued. You will be notified once it is complete.'
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hobbies_helper.rb
module HobbiesHelper
end

app/helpers/nav_helper.rb
module NavHelper
  def nav_link_to(name = nil, options = {}, html_options = {}, &block)
    name, options, html_options = block, name, options if block

    url = url_for(options)
    starts_with = html_options.delete(:starts_with)
    html_options[:class] ||= []
    active_class = html_options.delete(:active_class) || 'is-active'
    inactive_class = html_options.delete(:inactive_class) || ''

    active = Array.wrap(starts_with).any? { |path| request.path.start_with?(path) } || request.path == url
    html_options[:class] << (active ? " #{active_class}" : " #{inactive_class}")

    html_options.except!(:class) if html_options[:class].empty?

    link_to(name, url, html_options, &block)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/hobbies/_form.html.erb
<%= form_with(model: hobby) do |form| %>
<%= render "shared/error_messages", resource: form.object %>

  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_area :description, rows: 4, class: "form-control" %>
  </div>

  <div class="inline">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/hobbies/_hobby.html.erb
<div id="<%= dom_id hobby %>" class="bg-white p-6 shadow-sm rounded overflow-hidden">
<p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= hobby.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= hobby.description %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this hobby", hobby, class: "btn btn-primary" %>
    <%= link_to 'Edit this hobby', edit_hobby_path(hobby), class: "btn btn-secondary" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/hobbies/edit.html.erb
<div class="row">
  <div class="mx-auto col-12 col-sm-9 col-md-6">
    <h1 class="fw-bold">Editing hobby</h1>

    <%= render "form", hobby: @hobby %>
    <hr class="my-4">
    <%= link_to "Show this hobby", @hobby, class: "btn btn-secondary" %>
    <%= link_to "Back to hobbies", hobbies_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/hobbies/index.html.erb
<div class="w-100">
  <% if notice.present? %>
    <div class="alert alert-success" role="alert"><%= notice %></div>
  <% end %>

  <div class="d-flex justify-content-between align-items-center mb-5">
    <h1 class="fw-bold">Hobbies</h1>
    <%= link_to 'New hobby', new_hobby_path, class: "btn btn-primary" %>
  </div>

  <div id="hobbies" class="d-flex flex-wrap gap-4">
    <%= render @hobbies %>
  </div>
</div>

app/views/hobbies/new.html.erb
<div class="row">
  <div class="mx-auto col-12 col-sm-9 col-md-6">
    <h1 class="fw-bold">New hobby</h1>

    <%= render "form", hobby: @hobby %>
    <hr class="my-4">
    <%= link_to "Show this hobby", @hobby, class: "btn btn-secondary" %>
    <%= link_to "Back to hobbies", hobbies_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/hobbies/show.html.erb
<div class="mx-auto w-100 d-flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <div class="alert alert-success" role="alert"><%= notice %></div>
    <% end %>

    <%= render @hobby %>
    <hr class="my-4">
    <div class="d-flex justify-content-between align-items-center">
      <%= link_to 'Edit this hobby', edit_hobby_path(@hobby), class: "btn btn-primary mx-1" %>
      <%= button_to 'Destroy this hobby', hobby_path(@hobby), method: :delete, class: "btn btn-secondary mx-1" %>
      <%= link_to 'Back to hobbies', hobbies_path, class: "btn btn-danger mx-1" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <%= Rails.application.class.module_parent_name %>
    </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= vite_client_tag %>
    <%= vite_javascript_tag 'application' %>
    <!--
      If using a TypeScript entrypoint file:
        vite_typescript_tag 'application'

      If using a .jsx or .tsx entrypoint, add the extension:
        vite_javascript_tag 'application.jsx'

      Visit the guide for more information: https://vite-ruby.netlify.app/guide/rails
    -->

  </head>

  <body class="is-fullheight">
    <div class="is-flex is-flex-direction-column" style="height: 100vh;">
      <%= render "shared/navbar" %>
      <%= render "shared/flash" %>
      <main class="p-5 is-flex-grow-1">
        <%= yield %>
      </main>
      <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container has-text-centered is-fullheight is-flex is-align-items-center is-justify-content-center">
  <div class="is-flex-grow-1">
    <h1 class="mb-5">Welcome <%= [current_user.first_name, current_user.last_name].join(' ') %>!</h1>
    <div class="columns box is-vcentered has-background-white-ter my-5">
      <div class="column">
        <% unless current_user.hobbies.blank? %>
          <div>
            <h2 class="mb-5">Hobbies</h2>
            <ul>
              <% current_user.hobbies.each do |hobby| %>
                <li><%= hobby.name %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
      </div>
      <div class="column">
        <div id="hobby-partner"></div>
      </div>
    </div>
    <%= link_to "Export Profile to CSV", profile_export_path, class: "button is-primary mt-5" %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container has-text-centered is-fullheight is-flex is-align-items-center is-justify-content-center">
  <div>
    <div class="is-size-1">Find people</div>
    <div class="is-size-1">with similar hobbies</div>
    <div class="is-size-1">in your neighborhood.</div>
    <% unless user_signed_in? %>
      <div class="buttons is-centered mt-5">
        <%= link_to "Sign up", new_user_registration_path, class: "button is-rounded is-size-4 is-primary" %>
        <%= link_to "Login", new_user_session_path, class: "button is-link is-size-4" %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div class="notification is-danger mb-6" role="alert">
    <div class="is-flex align-items-start is-justify-content-start">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" class="fill-current icon mr-4 mt-1" role="img" aria-labelledby="f1yx75u7nv0lvn6ck4z10w7lksjmk2f"><title id="f1yx75u7nv0lvn6ck4z10w7lksjmk2f">Icons/close outline</title><path d="M2.93 17.07A10 10 0 1 1 17.07 2.93 10 10 0 0 1 2.93 17.07zm1.41-1.41A8 8 0 1 0 15.66 4.34 8 8 0 0 0 4.34 15.66zm9.9-8.49L11.41 10l2.83 2.83-1.41 1.41L10 11.41l-2.83 2.83-1.41-1.41L8.59 10 5.76 7.17l1.41-1.41L10 8.59l2.83-2.83 1.41 1.41z"></path></svg>

      <div>
        <h4 class="has-text-weight-bold is-size-6 uppercase">
          <%= pluralize(resource.errors.count, "error") %> prohibited this article from being saved:
        </h4>
        <ul>
          <% resource.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |type, msg| %>
  <% if type == 'alert' %>
    <%= content_tag :div, msg, class: "notification is-danger is-light", role: :alert %>
  <% elsif type == 'notice' %>
    <%= content_tag :div, msg, class: "notification is-primary is-light", role: :alert %>
  <% else %>
    <%= content_tag :div, msg, class: "notification", role: :alert %>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer p-5 has-background-light">
  <div class="content has-text-centered">
    <p class="mb-0 is-size-5 has-text-weight-bold">
      <%= Rails.application.class.module_parent_name %>
    </p>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar has-background-light" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= nav_link_to Rails.application.class.module_parent_name, root_path, class: "navbar-item has-text-weight-bold is-size-5" %>

    <% if user_signed_in? %>
      <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    <% end %>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-end">
      <div class="navbar-item">
        <% if user_signed_in? %>
          <div class="buttons">
            <%= nav_link_to "Dashboard", pages_dashboard_path, class: "button", active_class: "is-primary", inactive_class: "is-light" %>
            <%= nav_link_to "Edit profile", edit_user_registration_path, class: "button", active_class: "is-primary", inactive_class: "is-light" %>
            <%= button_to t(".sign_out"), destroy_user_session_path, method: :delete, class: "button is-danger is-light" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</nav>